# Входные файлы
input_txt: "bildstein_station3_xyz_intensity_rgb.txt"
input_label: "../../../../datasets/sem8_labels_training/bildstein_station3_xyz_intensity_rgb.labels"

# Папка вывода
output_dir: "./outputs"

# Нормализация
normalize:
  rgb_divide_by_255: true
  coords_method: "center_scale"   # options: center_scale, minmax, zscore
  normalize_intensity: true
  intensity_method: "max"         # options: max, minmax, zscore

# Какие форматы сохранять
outputs:
  formats: [npy] # options: npy, txt, h5
  npy_name: "semantic3d_dataset.npy"
  txt_name: "semantic3d_dataset.txt"
  h5_name: "semantic3d_dataset.h5"

# Логирование
log_level: INFO

# Аугментации
rotation:
  apply: true
  angles: [0.01, 0.02, 0.03]   # углы в радианах
  axes: "xyz"               # оси вращения (вращения покоординатно по порядку указанному в строке)
  inplace: true

gaussian_noise:
  apply: true
  std: 1.0
  inplace: true

uniform_noise:
  apply: true
  low: -0.5
  high: 0.5
  inplace: true